.\" Manpage for gcalcli.
.TH man 1 "25 February 2019" "4.0.4" "gcalcli Manual"
.SH NAME
gcalcli \- interact with a Google Calendar
.SH SYNOPSIS
gcalcli [options] command [command args or options]
.SH DESCRIPTION
gcalcli is a Python application that allows you to access your Google
Calendar(s) from a command line. It's easy to get your agenda, search for
events, add new events, delete events, edit events, and even import those
annoying ICS/vCal invites from Microsoft Exchange and/or other sources.
Additionally, gcalcli can be used as a reminder service and execute any
application you want when an event is coming up.
.SH USAGE

usage: gcalcli [-h] [--version] [--client-id CLIENT_ID] [--client-secret CLIENT_SECRET]
               [--noauth_local_server] [--config-folder CONFIG_FOLDER] [--noincluderc]
               [--calendar CALENDAR] [--default-calendar DEFAULTCALENDAR] [--locale LOCALE] [--refresh]
               [--nocache] [--conky] [--nocolor] [--lineart {fancy,unicode,ascii}]
               {list,search,edit,delete,agenda,agendaupdate,updates,conflicts,calw,calm,quick,add,import,remind}
               ...

Google Calendar Command Line Interface

positional arguments:
  {list,search,edit,delete,agenda,agendaupdate,updates,conflicts,calw,calm,quick,add,import,remind}
                        Invoking a subcommand with --help prints subcommand usage.
    list                list available calendars
    search              search for events within an optional time period
    edit                edit calendar events
    delete              delete events from the calendar
    agenda              get an agenda for a time period
    agendaupdate        update calendar from agenda TSV file
    updates             get updates since a datetime for a time period (defaults to through end of current
                        month)
    conflicts           find event conflicts
    calw                get a week-based agenda in calendar format
    calm                get a month agenda in calendar format
    quick               quick-add an event to a calendar
    add                 add a detailed event to the calendar
    import              import an ics/vcal file to a calendar
    remind              execute command if event occurs within <mins> time

options:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  --client-id CLIENT_ID
                        API client_id (default:
                        232867676714.apps.googleusercontent.com)
  --client-secret CLIENT_SECRET
                        API client_secret (default: 3tZSxItw6_VnZMezQwC8lUqy)
  --noauth_local_server
                        Provide instructions for authenticating from a remote system using port
                        forwarding. Note: Previously this option invoked an "Out-Of-Band" variant of the
                        auth flow, but that deprecated mechanism is no longer supported. (default: True)
  --config-folder CONFIG_FOLDER
                        Optional directory to load/store all configuration
                        information (default: None)
  --noincluderc         Whether to include ~/.gcalclirc when using
                        configFolder (default: True)
  --calendar CALENDAR   Which calendars to use (default: [])
  --default-calendar DEFAULT_CALENDAR
                        Optional default calendar to use if no --calendar
                        options are given (default: [])
  --locale LOCALE       System locale (default: )
  --refresh             Delete and refresh cached data (default: False)
  --conky               Use Conky color codes (default: False)
  --nocache             Execute command without using cache (default: True)
  --lineart {fancy,unicode,ascii}
                        Choose line art style for calendars: "fancy": for
                        VTcodes, "unicode" for Unicode box drawing characters,
                        "ascii" for old-school plusses, hyphens and pipes.
                        (default: fancy)
  --nocolor             Enable/Disable all color output (default: True)


.SH DIAGNOSTICS
.B "Encoding issues, wrongly printed characters, UnicodeEncodeError when using
conky, in pipes or scripts"
.RS
 - Set an environment variable PYTHONIOENCODING=utf8
 - Use a Unicode capable font like DejaVu Sans Mono
 - Set option --lineart=unicode or --lineart=ascii
 - Upgrade to Python3
.RE
.B "No colors or garbage characters when using inside conky"
.RS
 - Set option --conky
.RE
.SH SEE ALSO
bash(1)

.SH BUGS REPORTS
Report issues at https://github.com/insanum/gcalcli/issues
.SH AUTHORS

Eric Davis (edavis@insanum.com)

Brian Hartvigsen (brian.andrew@brianandjenny.com)

Joshua Crowgey (jcrowgey@uw.edu)
