__program__ = 'gcalcli'
__version__ = 'v4.3.0'
__author__ = 'Eric Davis, Brian Hartvigsen, Joshua Crowgey'
__API_CLIENT_ID__ = '232867676714.apps.googleusercontent.com'
__API_CLIENT_SECRET__ = '3tZSxItw6_VnZMezQwC8lUqy'
