name: Tests (tox)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - '*.md'
      - ChangeLog
      - LICENSE
      - docs/**

permissions:
  contents: read

jobs:
  test:
    name: test with ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.12"
          - "3.11"
          - "3.10"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    env:
      SKIP_ENVS: ${{ (matrix.py != '3.12' || matrix.os == 'windows-latest') && '--skip-env=cli' || '' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: ${{ matrix.py == '3.12' && matrix.os != 'windows-latest' && 'true' || 'false' }}
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - name: Install tox-gh
        run: python -m pip install tox-gh>=1.2
      - name: Setup test suite
        run: tox -vv --notest
      - name: Run test suite
        run: tox --skip-pkg-install ${{ env.SKIP_ENVS }}
